name: uni_links
description: Flutter plugin for accepting incoming links - App/Deep Links (Android), Universal Links and Custom URL schemes (iOS).
version: 0.4.0
homepage: https://github.com/avioli/uni_links

dependencies:
  flutter:
    sdk: flutter
  # uni_links_platform_interface: ^1.0.0
  uni_links_platform_interface:
    git:
      url: https://github.com/matanshukry/uni_links.git
      ref: uni_links_platform_interface-v1.0.0
      path: uni_links_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  # pedantic: ^1.9.0 # can't include due to bug. More details at analysis_options.yaml

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: name.avioli.unilinks
        pluginClass: UniLinksPlugin
      ios:
        pluginClass: UniLinksPlugin

