name: uni_links_platform_interface
description: A common platform interface for the uni_links plugin.
homepage: https://github.com/avioli/uni_links/tree/master/uni_links_platform_interface
version: 1.0.0

dependencies:
  meta: ^1.1.8
  plugin_platform_interface: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"